#
# Python modules are needed to run tests and check results
#    Also include gfortran and netCDF for development
#
name: rte_rrtmgp_dev
dependencies:
variables:
  FC: gfortran
  # Debugging flags below
  # Shell environment variables can't be used within this YML files, so
  # Users still need to set RRTMGP_ROOT,
  #  FCINCLUDE=-I${CONDA_PREFIX}/include
